server.port=8080

# Максимальный размер загружаемого файла
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Годовой план скрининга ХВГС (количество исследований)
screening.annual-plan=430270

# Учётные данные администратора (ОБЯЗАТЕЛЬНО сменить в продакшн через application-prod.properties)
app.admin.username=admin
app.admin.password=admin

# Папка где хранятся загруженные файлы-архивы (Excel)
# Пример для Windows: report.upload.dir=C:/Users/ИМЯ/emias-uploads
# Пример для Mac:     report.upload.dir=/Users/ИМЯ/emias-uploads
report.upload.dir=/Users/123ira456rambler.ru/Downloads/emias-uploads

# База данных H2 — файл ./data/emias_db.mv.db рядом с проектом
spring.datasource.url=jdbc:h2:file:./data/emias_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Автоматически создаёт/обновляет таблицы при запуске
spring.jpa.hibernate.ddl-auto=update

# Веб-консоль H2: открывается в браузере на http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Логирование в файл
logging.file.name=./logs/app.log
app.upload-log.file=./logs/upload.log
logging.level.com.emias.dashboard=DEBUG
